bot:
  name: "р╕Ьр╕╣р╣Йр╕Кр╣Ир╕зр╕вр╣Бр╕гр╕Зр╕Зр╕▓р╕Щр╣Др╕Чр╕в"
  language: th
  country: thailand

messages:
  welcome: |
    ЁЯСЛ р╕кр╕зр╕▒р╕кр╕Фр╕╡р╕Др╕гр╕▒р╕Ъ! р╕Ьр╕бр╣Ар╕Ыр╣Зр╕Щр╕Ьр╕╣р╣Йр╕Кр╣Ир╕зр╕вр╕кр╕│р╕лр╕гр╕▒р╕Ър╣Бр╕гр╕Зр╕Зр╕▓р╕Щр╣Др╕Чр╕вр╣Гр╕Щр╣Др╕Хр╣Йр╕лр╕зр╕▒р╕Щ

    р╕Ьр╕бр╕Кр╣Ир╕зр╕вр╣Др╕Фр╣Йр╣Ар╕гр╕╖р╣Ир╕нр╕З:
    - р╕Ър╕гр╕┤р╕Бр╕▓р╕гр╕кр╕╕р╕Вр╕ар╕▓р╕Ю
    - р╕кр╕┤р╕Чр╕Шр╕┤р╣Бр╕гр╕Зр╕Зр╕▓р╕Щ
    - р╕Кр╕╡р╕зр╕┤р╕Хр╕Ыр╕гр╕░р╕Ир╕│р╕зр╕▒р╕Щ
    - р╣Бр╕Ыр╕ер╕ар╕▓р╕йр╕▓

    р╕Цр╕▓р╕бр╣Др╕Фр╣Йр╣Ар╕ер╕вр╕Др╕гр╕▒р╕Ъ!

  help: |
    ЁЯУЛ р╕Ьр╕бр╕Кр╣Ир╕зр╕вр╣Др╕Фр╣Йр╣Ар╕гр╕╖р╣Ир╕нр╕З:
    - р╕Вр╣Йр╕нр╕бр╕╣р╕ер╕кр╕╕р╕Вр╕ар╕▓р╕Юр╣Бр╕ер╕░р╣Вр╕гр╕Зр╕Юр╕вр╕▓р╕Ър╕▓р╕е
    - р╕кр╕┤р╕Чр╕Шр╕┤р╕Вр╕нр╕Зр╣Бр╕гр╕Зр╕Зр╕▓р╕Щ
    - р╕Кр╕╡р╕зр╕┤р╕Хр╕Ыр╕гр╕░р╕Ир╕│р╕зр╕▒р╕Щр╣Гр╕Щр╣Др╕Хр╣Йр╕лр╕зр╕▒р╕Щ
    - р╣Бр╕Ыр╕ер╕ар╕▓р╕йр╕▓

    р╕Цр╕▓р╕бр╣Ар╕Ыр╣Зр╕Щр╕ар╕▓р╕йр╕▓р╣Др╕Чр╕вр╣Др╕Фр╣Йр╣Ар╕ер╕вр╕Др╕гр╕▒р╕Ъ!

  cleared: "тЬЕ р╕ер╕Ър╕Ыр╕гр╕░р╕зр╕▒р╕Хр╕┤р╕Бр╕▓р╕гр╕кр╕Щр╕Чр╕Щр╕▓р╣Бр╕ер╣Йр╕з"

  unknown_command: "тЭУ р╣Др╕бр╣Ир╕гр╕╣р╣Йр╕Ир╕▒р╕Бр╕Др╕│р╕кр╕▒р╣Ир╕Зр╕Щр╕╡р╣Й"

  error: "р╕Вр╕нр╕нр╕ар╕▒р╕в р╕бр╕╡р╕Вр╣Йр╕нр╕Ьр╕┤р╕Фр╕Юр╕ер╕▓р╕Ф р╕Бр╕гр╕╕р╕Ур╕▓р╕ер╕нр╕Зр╣Гр╕лр╕бр╣И"

emergency:
  police: "110"
  ambulance: "119"
  labor_hotline: "1955"
  embassy: "р╕кр╕│р╕Щр╕▒р╕Бр╕Зр╕▓р╕Щр╕Бр╕▓р╕гр╕Др╣Йр╕▓: 02-2581-1979"
  consular: "Hotline: 0912-151-051"

quick_replies:
  - label: "ЁЯПе р╕кр╕╕р╕Вр╕ар╕▓р╕Ю"
    text: "р╕Хр╣Йр╕нр╕Зр╕Бр╕▓р╕гр╕Др╕зр╕▓р╕бр╕Кр╣Ир╕зр╕вр╣Ар╕лр╕ер╕╖р╕нр╕Фр╣Йр╕▓р╕Щр╕кр╕╕р╕Вр╕ар╕▓р╕Ю"
  - label: "ЁЯТ╝ р╕Зр╕▓р╕Щ"
    text: "р╕бр╕╡р╕Ыр╕▒р╕Нр╕лр╕▓р╕Чр╕╡р╣Ир╕Чр╕│р╕Зр╕▓р╕Щ"
  - label: "ЁЯЪи р╕Йр╕╕р╕Бр╣Ар╕Йр╕┤р╕Щ"
    text: "р╣Ар╕лр╕Хр╕╕р╕Йр╕╕р╕Бр╣Ар╕Йр╕┤р╕Щ!"
